version: '3'
services:
  jenkins:
    build:
      context: ./
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    hostname: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
